inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - "spec/**/*"
    - "test/**/*"
    - "bin/**/*"

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/rails-query-tracer.rb'
